
package com.mycompany.server.wsauthclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Auth_serviceService", targetNamespace = "http://auth.vniias", wsdlLocation = "http://host_a:port_a/auth_service/services/Auth_service/wsdl/Auth_service.wsdl")
public class AuthServiceService
    extends Service
{

    private final static URL AUTHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHSERVICESERVICE_EXCEPTION;
    private final static QName AUTHSERVICESERVICE_QNAME = new QName("http://auth.vniias", "Auth_serviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://host_a:port_a/auth_service/services/Auth_service/wsdl/Auth_service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHSERVICESERVICE_WSDL_LOCATION = url;
        AUTHSERVICESERVICE_EXCEPTION = e;
    }

    public AuthServiceService() {
        super(__getWsdlLocation(), AUTHSERVICESERVICE_QNAME);
    }

    public AuthServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHSERVICESERVICE_QNAME, features);
    }

    public AuthServiceService(URL wsdlLocation) {
        super(wsdlLocation, AUTHSERVICESERVICE_QNAME);
    }

    public AuthServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHSERVICESERVICE_QNAME, features);
    }

    public AuthServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthService
     */
    @WebEndpoint(name = "Auth_service")
    public AuthService getAuthService() {
        return super.getPort(new QName("http://auth.vniias", "Auth_service"), AuthService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthService
     */
    @WebEndpoint(name = "Auth_service")
    public AuthService getAuthService(WebServiceFeature... features) {
        return super.getPort(new QName("http://auth.vniias", "Auth_service"), AuthService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHSERVICESERVICE_EXCEPTION!= null) {
            throw AUTHSERVICESERVICE_EXCEPTION;
        }
        return AUTHSERVICESERVICE_WSDL_LOCATION;
    }

}
