
package com.mycompany.server.wsauthclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Auth_service", targetNamespace = "http://auth.vniias")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthService {


    /**
     * 
     * @param idProg
     * @return
     *     returns com.mycompany.server.wsauthclient.ArrayOfUserInfo
     * @throws NsiException_Exception
     */
    @WebMethod(action = "getUsersByProg")
    @WebResult(name = "getUsersByProgReturn", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByProg", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetUsersByProg")
    @ResponseWrapper(localName = "getUsersByProgResponse", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetUsersByProgResponse")
    public ArrayOfUserInfo getUsersByProg(
        @WebParam(name = "id_prog", targetNamespace = "")
        int idProg)
        throws NsiException_Exception
    ;

    /**
     * 
     * @param pwd
     * @param idProg
     * @param clientVersion
     * @param user
     * @param ip
     * @return
     *     returns com.mycompany.server.wsauthclient.UserInfo
     * @throws InvalidVersionException_Exception
     * @throws NsiException_Exception
     */
    @WebMethod(action = "login2")
    @WebResult(name = "login2Return", targetNamespace = "")
    @RequestWrapper(localName = "login2", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.Login2")
    @ResponseWrapper(localName = "login2Response", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.Login2Response")
    public UserInfo login2(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd,
        @WebParam(name = "ip", targetNamespace = "")
        String ip,
        @WebParam(name = "id_prog", targetNamespace = "")
        int idProg,
        @WebParam(name = "client_version", targetNamespace = "")
        String clientVersion)
        throws InvalidVersionException_Exception, NsiException_Exception
    ;

    /**
     * 
     * @param login
     * @return
     *     returns com.mycompany.server.wsauthclient.ArrayOfXsdNillableInt
     * @throws NsiException_Exception
     */
    @WebMethod(action = "getProgsIdByUser")
    @WebResult(name = "getProgsIdByUserReturn", targetNamespace = "")
    @RequestWrapper(localName = "getProgsIdByUser", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetProgsIdByUser")
    @ResponseWrapper(localName = "getProgsIdByUserResponse", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetProgsIdByUserResponse")
    public ArrayOfXsdNillableInt getProgsIdByUser(
        @WebParam(name = "login", targetNamespace = "")
        String login)
        throws NsiException_Exception
    ;

    /**
     * 
     * @param pwd
     * @param idProg
     * @param user
     * @return
     *     returns com.mycompany.server.wsauthclient.UserInfo
     * @throws NsiException_Exception
     */
    @WebMethod(action = "login")
    @WebResult(name = "loginReturn", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.LoginResponse")
    public UserInfo login(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd,
        @WebParam(name = "id_prog", targetNamespace = "")
        int idProg)
        throws NsiException_Exception
    ;

    /**
     * 
     * @param user
     * @param pass
     * @return
     *     returns com.mycompany.server.wsauthclient.ArrayOfUpdateInfo
     * @throws NsiException_Exception
     */
    @WebMethod(action = "getSystemUpdateInfo")
    @WebResult(name = "getSystemUpdateInfoReturn", targetNamespace = "")
    @RequestWrapper(localName = "getSystemUpdateInfo", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetSystemUpdateInfo")
    @ResponseWrapper(localName = "getSystemUpdateInfoResponse", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetSystemUpdateInfoResponse")
    public ArrayOfUpdateInfo getSystemUpdateInfo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws NsiException_Exception
    ;

    /**
     * 
     * @param pwd
     * @param login
     * @return
     *     returns com.mycompany.server.wsauthclient.ArrayOfXsdNillableInt
     * @throws NsiException_Exception
     */
    @WebMethod(action = "getProgsIdByUserPwd")
    @WebResult(name = "getProgsIdByUserPwdReturn", targetNamespace = "")
    @RequestWrapper(localName = "getProgsIdByUserPwd", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetProgsIdByUserPwd")
    @ResponseWrapper(localName = "getProgsIdByUserPwdResponse", targetNamespace = "http://auth.vniias", className = "com.mycompany.server.wsauthclient.GetProgsIdByUserPwdResponse")
    public ArrayOfXsdNillableInt getProgsIdByUserPwd(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd)
        throws NsiException_Exception
    ;

}
