
package com.mycompany.server.wsauthclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidVersionException", targetNamespace = "http://auth.vniias")
public class InvalidVersionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidVersionException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidVersionException_Exception(String message, InvalidVersionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidVersionException_Exception(String message, InvalidVersionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.mycompany.server.wsauthclient.InvalidVersionException
     */
    public InvalidVersionException getFaultInfo() {
        return faultInfo;
    }

}
