
package com.mycompany.server.wsauthclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NsiException", targetNamespace = "http://auth.vniias")
public class NsiException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NsiException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NsiException_Exception(String message, NsiException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NsiException_Exception(String message, NsiException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.mycompany.server.wsauthclient.NsiException
     */
    public NsiException getFaultInfo() {
        return faultInfo;
    }

}
